/*******************************************************************
 * @file     custom_ddr.h is generated by ddrmctl2_PAIS_Tool
 * @version  v3.11
 * @date     2023/10/18 ¤W¤È 09:58:10
 * @brief    DDR settings header file
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright (C) 2023 Nuvoton Technology Corp. All rights reserved.
********************************************************************/

/**************************Chip system parameters*******************
Frequency of APB interface clock of DDR memory controller.......90
DDR DRAM types..................................................DDR2
DDR Data Rate...................................................1066
DRAM size per device............................................128
Number of ranks that system chip connects to used DRAM..........1
Bit number of bank address for used DRAM........................3
Bit number of row address for used DRAM.........................13
Bit number of column address for used DRAM......................10
Output driver impedance for used DDR2...........................Normal
ODT(On Die Termination) for used DDR2...........................75
Output driver impedance for DDR2 PHY............................40
ODT(On Die Termination) for DDR2 PHY............................75
********************************************************************/

/**************************DRAM timing parameters*******************
            tCK        ns     Final
CL:           7         -         7
tRCD:         -     11.25         6
tRP:          -     11.25         6
tRC:          -     51.25        27
tRAS_max:     -     70000     37310
tRAS_min:     -        40        21
tRTP:         -       7.5         4
tWTR:         -       7.5         4
tWR:          -        15         8
tMRD:         2         -         2
tCCD:         2         -         2
tRRD:         -        10         5
tFAW:         -        45        24
tXSNR:        -     137.5        73
tXSRD:      200         -       200
tRFC:         -     127.5        68
tREFI:        -      1950      1039
tXP:          3         -         3
tCKE:         3         -         3
tXARD:        3         -         3
tXARDS:      10         -        10
********************************************************************/

#ifndef __NVT_DDR_INIT_PARAM_H__
#define __NVT_DDR_INIT_PARAM_H__


struct nvt_ddr_init_param custom_ddr= {
       0x00000001,  //DBG1
       0x00000001,  //PWRCTL
       0x01040000,  //MSTR
       0x0000D010,  //MRCTRL0
       0x00000000,  //MRCTRL1
       0x00000000,  //PWRCTL
       0x00400010,  //PWRTMG
       0x000A0003,  //HWLPCTL
       0x00210000,  //RFSHCTL0
       0x003C003C,  //RFSHCTL1
       0x00000000,  //RFSHCTL3
       0x000F0023,  //RFSHTMG
       0x00000000,  //CRCPARCTL0
       0x40020035,  //INIT0
       0x00010002,  //INIT1
       0x0E730004,  //INIT3
       0x00800000,  //INIT4
       0x00090000,  //INIT5
       0x00000000,  //DIMMCTL
       0x0000031F,  //RANKCTL
       0x0A0D100C,  //DRAMTMG0
       0x0003040F,  //DRAMTMG1
       0x00000508,  //DRAMTMG2
       0x00002004,  //DRAMTMG3
       0x04020404,  //DRAMTMG4
       0x01010303,  //DRAMTMG5
       0x00000503,  //DRAMTMG8
       0x00000000,  //DRAMTMG15
       0xC0000000,  //ZQCTL0
       0x00000100,  //ZQCTL1
       0x04020101,  //DFITMG0
       0x00060101,  //DFITMG1
       0x0700B030,  //DFILPCFG0
       0x00400005,  //DFIUPD0
       0x00170066,  //DFIUPD1
       0x80000000,  //DFIUPD2
       0x00000011,  //DFIMISC
       0x00000000,  //DFIPHYMSTR
       0x0000001F,  //ADDRMAP0
       0x00080808,  //ADDRMAP1
       0x00000000,  //ADDRMAP2
       0x00000000,  //ADDRMAP3
       0x00001F1F,  //ADDRMAP4
       0x070F0707,  //ADDRMAP5
       0x0F0F0F07,  //ADDRMAP6
       0x07070707,  //ADDRMAP9
       0x07070707,  //ADDRMAP10
       0x00000007,  //ADDRMAP11
       0x07010708,  //ODTCFG
       0x00000101,  //ODTMAP
       0x00F51F00,  //SCHED
       0x00000000,  //SCHED1
       0x0F000001,  //PERFHPR1
       0x0F00007F,  //PERFLPR1
       0x0F00007F,  //PERFWR1
       0x00000000,  //DBG0
       0x00000000,  //DBG1
       0x00000000,  //DBGCMD
       0x00000001,  //SWCTL
       0x00000000,  //SWCTLSTATIC
       0x00110011,  //POISONCFG
       0x00000001,  //PCTRL_0
       0x00000000,  //PCTRL_1
       0x00000000,  //PCTRL_2
       0x00000000,  //PCTRL_3
       0x00000000,  //PCTRL_4
       0x00000001,  //PCTRL_5
       0x00000001,  //PCTRL_6
       0x00000000,  //PCCFG
       0x0001500F,  //PCFGR_0
       0x0001500F,  //PCFGR_1
       0x0001500F,  //PCFGR_2
       0x0001500F,  //PCFGR_3
       0x0001500F,  //PCFGR_4
       0x0001500F,  //PCFGR_5
       0x0001500F,  //PCFGR_6
       0x0000500F,  //PCFGW_0
       0x0000500F,  //PCFGW_1
       0x0000500F,  //PCFGW_2
       0x0000500F,  //PCFGW_3
       0x0000500F,  //PCFGW_4
       0x0000500F,  //PCFGW_5
       0x0000500F,  //PCFGW_6
       0x00000008,  //SARBASE0
       0x00000000,  //SARSIZE0
       0xF004649F,  //DSGCR
       0x0300C461,  //PGCR1
       0x00F0027F,  //PGCR2
       0x0B405A03,  //PTR0
       0x2328032B,  //PTR1
       0x00083DEF,  //PTR2
       0x0D71A069,  //PTR3
       0x00000000,  //PTR4
       0x00000E73,  //MR0_DDR2
       0x00000004,  //MR1_DDR2
       0x00000080,  //MR2_DDR2
       0x00000000,  //MR3_DDR2
       0x75D77755,  //DTPR0
       0x00022B23,  //DTPR1
       0x00022CC9,  //DTPR2
       0x0000104B,  //ZQ0CR1
       0x0000040A,  //DCR
       0x91003587,  //DTCR
       0x0001C000,  //PLLCR
       0x0000F501,  //PIR
       0x00000000,  //SWCTL
       0x0000000B,  //PWRCTL
       0x00000001,  //SWCTL
};


#endif