/*******************************************************************
 * @file     custom_ddr.h is generated by ddrmctl2_PAIS_Tool
 * @version  v3.04
 * @date     3/17/2023 3:03:04 PM
 * @brief    DDR settings header file
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright (C) 2023 Nuvoton Technology Corp. All rights reserved.
********************************************************************/

#ifndef __NVT_DDR_INIT_PARAM_H__
#define __NVT_DDR_INIT_PARAM_H__


struct nvt_ddr_init_param custom_ddr= {
       0x00000001,  //DBG1
       0x00000001,  //PWRCTL
       0x03040001,  //MSTR
       0x0000d030,  //MRCTRL0
       0x00000000,  //MRCTRL1
       0x00000000,  //PWRCTL
       0x00400010,  //PWRTMG
       0x000a0003,  //HWLPCTL
       0x00210000,  //RFSHCTL0
       0x003c003c,  //RFSHCTL1
       0x00000000,  //RFSHCTL3
       0x00100046,  //RFSHTMG
       0x00000000,  //CRCPARCTL0
       0x40020083,  //INIT0
       0x00350002,  //INIT1
       0x1b400084,  //INIT3
       0x00480000,  //INIT4
       0x00090000,  //INIT5
       0x00000000,  //DIMMCTL
       0x0000032f,  //RANKCTL
       0x090d040a,  //DRAMTMG0
       0x0003020e,  //DRAMTMG1
       0x00000408,  //DRAMTMG2
       0x00003007,  //DRAMTMG3
       0x04020205,  //DRAMTMG4
       0x03030202,  //DRAMTMG5
       0x00000a04,  //DRAMTMG8
       0x80000032,  //DRAMTMG15
       0x00800020,  //ZQCTL0
       0x00000100,  //ZQCTL1
       0x04020101,  //DFITMG0
       0x00060101,  //DFITMG1
       0x0700b030,  //DFILPCFG0
       0x00400005,  //DFIUPD0
       0x00170066,  //DFIUPD1
       0x80000000,  //DFIUPD2
       0x00000011,  //DFIMISC
       0x00000000,  //DFIPHYMSTR
       0x00000016,  //ADDRMAP0
       0x00080808,  //ADDRMAP1
       0x00000000,  //ADDRMAP2
       0x00000000,  //ADDRMAP3
       0x00001f1f,  //ADDRMAP4
       0x070f0707,  //ADDRMAP5
       0x0f070707,  //ADDRMAP6
       0x07070707,  //ADDRMAP9
       0x07070707,  //ADDRMAP10
       0x00000007,  //ADDRMAP11
       0x06000608,  //ODTCFG
       0x00000303,  //ODTMAP
       0x00f51f00,  //SCHED
       0x00000000,  //SCHED1
       0x0f000001,  //PERFHPR1
       0x0f00007f,  //PERFLPR1
       0x0f00007f,  //PERFWR1
       0x00000000,  //DBG0
       0x00000000,  //DBG1
       0x00000000,  //DBGCMD
       0x00000001,  //SWCTL
       0x00000000,  //SWCTLSTATIC
       0x00110011,  //POISONCFG
       0x00000001,  //PCTRL_0
       0x00000000,  //PCTRL_1
       0x00000000,  //PCTRL_2
       0x00000000,  //PCTRL_3
       0x00000000,  //PCTRL_4
       0x00000001,  //PCTRL_5
       0x00000001,  //PCTRL_6
       0x00000000,  //PCCFG
       0x0001500f,  //PCFGR_0
       0x0001500f,  //PCFGR_1
       0x0001500f,  //PCFGR_2
       0x0001500f,  //PCFGR_3
       0x0001500f,  //PCFGR_4
       0x0001500f,  //PCFGR_5
       0x0001500f,  //PCFGR_6
       0x0000500f,  //PCFGW_0
       0x0000500f,  //PCFGW_1
       0x0000500f,  //PCFGW_2
       0x0000500f,  //PCFGW_3
       0x0000500f,  //PCFGW_4
       0x0000500f,  //PCFGW_5
       0x0000500f,  //PCFGW_6
       0x00000008,  //SARBASE0
       0x00000003,  //SARSIZE0
       0xf004649f,  //DSGCR
       0x0300c461,  //PGCR1
       0x00f0027f,  //PGCR2
       0x0c806403,  //PTR0
       0x27100385,  //PTR1
       0x00083def,  //PTR2
       0x0904111d,  //PTR3
       0x0801a072,  //PTR4
       0x00001b40,  //MR0_DDR3
       0x00000084,  //MR1_DDR3
       0x00000048,  //MR2_DDR3
       0x00000000,  //MR3_DDR3
       0x71568855,  //DTPR0
       0x2284632a,  //DTPR1
       0x30023e00,  //DTPR2
       0x0000105d,  //ZQ0CR1
       0x0000040b,  //DCR
       0x93003587,  //DTCR
       0x0005C000,  //PLLCR
       0x0000ff81,  //PIR
       0x00000000,  //SWCTL
       0x0000000B,  //PWRCTL
       0x00000001,  //SWCTL
};


#endif